version: "3.8"

services:
  mysqldb:
    build: ./db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
    networks:
      - test_nttdata

  client:
      build:
        context: ./client
      ports:
        - "8080:8080"
      networks:
        - test_nttdata

  account:
      build:
        context: ./account
      ports:
        - "8090:8090"
      depends_on:
        - mysqldb
      networks:
        - test_nttdata


volumes:
  db:

networks:
  test_nttdata:
    driver: bridge